name: watch-star-activity

on:
  watch:
    types:
      - started

jobs:
  handle-stars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run star handler script
        env:
          GITHUB_TOKEN: ${{ secrets.STAR_BOT_GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event.action }}" == "started" ]; then
            echo "Repo starred by ${{ github.event.sender.login }}"
          elif [ "${{ github.event.action }}" == "deleted" ]; then
            echo "Repo unstarred by ${{ github.event.sender.login }}"
          fi
